### PR TITLE
added snap workflow to build and release it

### PR DESCRIPTION
**Pull request by soumyaDghosh**
Needs some testing with the workflow, because this is the first time I'm experimenting. This workflow removes need to go to the store at all. Everything can be controlled from within this repo. The additionals needed are

two environment variables

1.` LAUNCHPAD_TOKEN`: for this, should I share my launchpad token, or will you create an account in launchpad and use that token?
2. `SNAP_STORE_TOKEN`: This can be obtained by running this command

```bash
snapcraft export-login --snaps=folio --acls package_access,package_push,package_update,package_release exported.txt
```
After running this command, you'll see a `exported.txt` file, set the content of that file as `SNAP_STORE_TOKEN`.

### CODE REVIEW

**Comment by toolstack** [comment]
Thanks, could you split this into two PRs?  One for the snapcraft.yaml and one for the actions?

**Comment by soumyaDghosh** [comment]
Done!

**Comment by toolstack** [comment]
I'll do the first release manually and then look at merging this after I have some experience with the packaging format.

**Comment by soumyaDghosh** [comment]
We can always control the release from the store. Also, if you can add me as a collaborator of the snap, I can also keep an eye on it.

This is my email id to add `soumyadeepghosh2004@zohomail.in`

**Comment by toolstack** [comment]
I'm going to close this, I've created an action to build he snap, but I don't think I'll auto deploy it.

**Pull request closed without merging**
