### PR TITLE
Initial Hindi translation

### PR DESCRIPTION
**Pull request by Scrambled777**
Adds Hindi `hi` language translation.

### CODE REVIEW

**Comment by toolstack** [comment]
Great, thanks for the PR.

Let me know if you want to maintain this over on the translation site I setup as well.

**Comment by Scrambled777** [comment]
> Let me know if you want to maintain this over on the translation site I setup as well.

I don't mind maintaining on online platform. Personally, I prefer to do translation offline and upload on the platform. 

Is it possible to download and submit `po` file?

**Comment by toolstack** [comment]
Yes, you can import/export the PO on the platform.

Drop me you're e-mail and I'll add you to it, thanks.

**Comment by Scrambled777** [comment]
@toolstack 

> Yes, you can import/export the PO on the platform.

That's sweet. 

> Drop me you're e-mail and I'll add you to it, thanks.

weblate.scrambled777@simplelogin.com

**Comment by toolstack** [comment]
Ok, I've created your account (you should have a e-mail to reset your password) and I've imported the Hindi translations you submitted.

I usually send out an e-mail a few days before a release to the translators if there are changes to the translations.

Thanks.

**Pull request merged**
