### PR TITLE
Update es.po (Spanish translation)

### PR DESCRIPTION
**Pull request by IngrownMink4**
### This patch brings these improvements:
- Rename all capitalized terms to lowercase. For example: “Crear Nota” -> “Crear nota”
- Improve some expressions that were too cumbersome.
- Rename the app to reflect that it is a fork (Paper -> Folio)

### CODE REVIEW

**Comment by toolstack** [comment]
Thanks.

**Comment by toolstack** [comment]
@IngrownMink4 I've also setup a translation site if your interested in maintaining the Spanish translation in the future.  If so send me an e-mail and I'll create you an account on it.

**Comment by IngrownMink4** [comment]
> @IngrownMink4 I've also setup a translation site if your interested in maintaining the Spanish translation in the future. If so send me an e-mail and I'll create you an account on it.

I was unaware of this platform. I will email you soon to maintain the translation, although I may not have time in the future.

**Comment by toolstack** [comment]
> I was unaware of this platform. I will email you soon to maintain the translation, although I may not have time in the future.

Sounds good, I only built it yesterday so no surprise you weren't aware of it 😉

**Pull request merged**
