### PR TITLE
Update runtime to GNOME 47

### PR DESCRIPTION
**Pull request by drpetrikov**

### CODE REVIEW

**Comment by toolstack** [comment]
Did you execute the compile and packaging to see if anything breaks?

**Comment by drpetrikov** [comment]
I've done it with 46 and nothing broke but i'll try again with 47

also, i love Folio so much, getting it updated would be amazing since G45 is soon end of life

**Comment by toolstack** [comment]
I think 46 should be fine, but I suspect there are a few deprecated functions that might impact using 47.  Since you tested 46, I'll double check it and certainly move to that for sure.

**Comment by toolstack** [comment]
Ok, looks like it's fine, will merge this change, thanks.

**Comment by drpetrikov** [comment]
Awesome! Do you have plans for a new release to update the runtime or is that not necessary?

**Comment by toolstack** [comment]
The runtime is fine at the moment, 45 is still supported, I have a few more bugs to track down before the next release, should be sometime this month would be my guess.

**Pull request merged**
